services:
  nginx-http:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx-http
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
